countries = [
    "Andorra",
    "Australia",
    "Argentina",
    "Bangladesh",
    "Belgium",
    "Bhutan",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Cambodia",
    "Canada",
    "Chile",
    "Croatia",
    "Colombia",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Hong Kong",
    "Iceland",
    "Indonesia",
    "Ireland",
    "Italy",
    "Israel",
    "Japan",
    "Latvia",
    "Lithuania",
    "Malaysia",
    "Mexico",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Peru",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "South Korea",
    "Spain",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Thailand",
    "Ukraine",
    "United Kingdom",
    "United States",
]
